pip install numpy
pip install scipy
pip install pillow
pip install opencv-python
pip install imageio
pip install lz4
pip install tqdm
pip install adbutils
pip install uiautomator2
pip install retrying
pip install mxnet
pip install cnocr
pip install jellyfish
pip install pyyaml
pip install inflection
pip install pywebio
pip install starlette
pip install anyio
pip install uvicorn[standard]
pip install aiofiles
pip install wrapt
pip install prettytable
pip install pypresence
pip install alas-webapp
pip install rich
pip install zerorpc
pip install pyzmq
pip install onepush